# This is a basic workflow to help you get started with Actions

name: Continuous Integration for kotlin app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" , "feature/branch" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Runs a custom script
        run: |
          ls -al

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with: |
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.awsaccesskey }}
          aws-secret-access-key: ${{ secrets.awssecretaccesskey }}

      - name: Run AWS CLI command
        run: aws s3 ls

      
    #  - name: Check Java Version
    #    run: java -version
    #  - name: Change the permissions for gradlew script to execute
    #    run: chmod +x gradlew
    #  - name: Build with gradlew
    #    run: ./gradlew build
    #  - name: Docker version
    #    run: |
    #      docker -v
    #      docker
    #      docker images -a
    #  - name: docker build
    #    run: |
    #      docker build -t saipavandocker2022/demo-kotlin:latest .
    #      docker images -a
    #  - name: docker login 
    #    run: docker login -u ${{ secrets.dockerhubusername }} -p ${{ secrets.dockerhubpassword }}
    #  - name: Docker image push to docker hub
    #    run: docker push saipavandocker2022/demo-kotlin:latest